[project]
name = "multimode-gripper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "opencv-contrib-python>=4.13.0.92",
    "piper-sdk>=0.6.1",
    "pyagxarm",
    "pybullet>=3.2.7",
    "pyrealsense2>=2.56.5.9235",
    "PyQt6>=6.0.0",
    "fonttools>=4.0.0",
]

[tool.uv.sources]
pyagxarm = { git = "https://github.com/agilexrobotics/pyAgxArm.git" }
